// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV3rkGacGwEIZfar7B4P25pKFFJsn0GVg',
    appId: '1:878910014917:web:52637a7b0e599c25eaf7ac',
    messagingSenderId: '878910014917',
    projectId: 'gawa-2728d',
    authDomain: 'gawa-2728d.firebaseapp.com',
    storageBucket: 'gawa-2728d.appspot.com',
    measurementId: 'G-D27SKVHB4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYV_d9QLXX6iALQAeB96CkGjG4swMlAY',
    appId: '1:878910014917:android:d63e64528a5bbf73eaf7ac',
    messagingSenderId: '878910014917',
    projectId: 'gawa-2728d',
    storageBucket: 'gawa-2728d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcooOmQuVPBwwaLOkVw95x_K2jjt1pono',
    appId: '1:878910014917:ios:c71b14a515b17406eaf7ac',
    messagingSenderId: '878910014917',
    projectId: 'gawa-2728d',
    storageBucket: 'gawa-2728d.appspot.com',
    iosBundleId: 'com.example.gawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcooOmQuVPBwwaLOkVw95x_K2jjt1pono',
    appId: '1:878910014917:ios:baa12c0a0c4fc350eaf7ac',
    messagingSenderId: '878910014917',
    projectId: 'gawa-2728d',
    storageBucket: 'gawa-2728d.appspot.com',
    iosBundleId: 'com.example.gawa.RunnerTests',
  );
}
